version: '3.5'

services:
   mdns-repeater:
    build:
        context: .
        dockerfile: Dockerfile
    network_mode: "host"
    privileged: true
    environment:
      INTERFACES: "eth0"
      DOCKER_NETWORKS: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock